script_path: /path/to/tutorial_folder/tutorial-torch-distributed-data-parallel/multi-GPU-training-torch.py
out_dir: /path/to/output_folder/tmp_out/torch
optional_args:
  set_epoch: true
  print_rand: false
local:
  device: cuda
  condor:
    bid: 50
    num_cpus: 2
    memory_cpus: 128000
    num_gpus: 2
    memory_gpus: 60000

